services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"
    env_file:
      - api/.env
    volumes:
      - mongodb-volume:/var/lib/mongodb/data

  node:
    container_name: node
    build: ./api
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    env_file:
      - api/.env
  
  front:
    container_name: front
    build: ./spa
    volumes:
      - front-volume:/var/www/html
  
  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs
  
  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - front-volume:/var/www/html
      - ssl-certs:/certs
    depends_on:
      - mongodb
      - node
      - front

volumes:
  mongodb-volume:
  front-volume:
  ssl-certs:
